export interface JobDetail {
    id: string,
    title: string,
    slug: string,
    description: string,
    requirements: string,
    benefits: string,
    salaryMin: number,
    salaryMax: number,
    type: string,
    experience: string,
    level: string,
    quantity: number,
    deadline: string | null,
    createdAt: string,
    company: {
        id: string,
        name: string,
        logo: string,
        website: string,
        description: string,
        size: string,
        industry: string,
        addressDetail: string,
        ward: { name: string, slug: string } | null
    },
    category: { name: string, slug: string },
    categoryId: string,
    ward: { name: string, slug: string } | null,
    wardId: string | null,
    addressDetail: string,
    quizId: string,
    latitude: number,
    longitude: number,
}